export enum BlockEnum {
  BlockHero = 'BlockHero',
  BlockAboutCourse = 'BlockAboutCourse',
  BlockAboutUs = 'BlockAboutUs',
  BlockScheduleLessons = 'BlockScheduleLessons',
  BlockFormatLessons = 'BlockFormatLessons',
  BlockFaq = 'BlockFaq',
  BlockAchivments = 'BlockAchivments',
  BlockBenefits = 'BlockBenefits',
  BlockContactForm = 'BlockContactForm',
  BlockTeamEducation = 'BlockTeamEducation',
  BlockRequirement = 'BlockRequirement',
  BlockContacts = 'BlockContacts',
  BlockCourseForPeople = 'BlockCourseForPeople',
  BlockCta = 'BlockCta',
  BlockOurBenefits = 'BlockOurBenefits',
  BlockStructEducation = 'BlockStructEducation',
  BlockWhoTeach = 'BlockWhoTeach',
  BlockSchedule = 'BlockSchedule',
  BlockAbout = 'BlockAbout',
  BlockReview = 'BlockReview',
  BlockBlog = 'BlockBlog',
  BlockContact = 'BlockContact',
  BlockRelatedPosts = 'BlockRelatedPosts',
}
